### ISSUE TITLE
when should I useEventListener in vue

### ISSUE THREAD

**Issue by colgin** [xus-code/vue-reuse#12]
After I read the doc, i still don't understand when should I useEventListener instead of @event in template.

useEventListener use ref to record the dom element, and use addEventListener to register event to the dom, remove listener after unmonuted, As i know, Vue runtime do all of that if you use @event to register event(Even cache the listener).

useEventListener expose the ref to template, @event expose event handler to template. So why we use useEventListener, is here some trade-off to design this api.

**Comment by xus-code** [comment]
most of the time v-on directive can do those things with template syntax，but sometimes we need composition-like or hooks-like style，we can use useEventListener; the most important is when we use jsx syntax without event modifiers we can use useEventListener to preventDefault、stopPropagation by addEventListenerOptions configuration or reuse some logic just like debounce、throttle.
